version: '3'

services:
  backend:
    container_name: 'backend'
    build: 
      context: backend
      dockerfile: Dockerfile
    networks:
      - backend
    env_file: .env
    restart: unless-stopped
    ports:
      - '4000:3000'
    depends_on:
      - database

  database:
    container_name: 'database'
    image: "postgres:12-alpine"
    restart: unless-stopped
    networks:
      - backend
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'


  frontend:
    container_name: 'frontend'
    build: 
      context: frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8081:80'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  db-data:

networks:
  backend:
