version: '3'

services:
  backend:
    container_name: 'backend'
    build: 
      context: backend
      dockerfile: Dockerfile
    networks:
      - backend
    env_file: .env
    restart: unless-stopped
    ports:
      - '4000:3000'
    depends_on:
      - postgres

  postgres:
    container_name: 'database'
    image: "postgres:12-alpine"
    restart: on-failure
    networks:
      - backend
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  frontend:
    container_name: 'frontend'
    build: 
      context: frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8081:80'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

  volumes:
    db-data:

  networks:
    backend:
